/**
 * Mock data for dashboard preview.
 * Replace with real API calls in production.
 */

import type { Site, DashboardData, MonthlyReport, TrendPoint } from './types';

export const BARNARDOS_SITE: Site = {
  id: 'barnardos',
  slug: 'barnardos-australia',
  client_name: 'Barnardos Australia',
  domain: 'barnardosaudev.wpengine.com',
  active: true,
  health_score: 62,
  traffic_light: 'RED',
  last_snapshot: '2026-05-07',
  pagespeed_mobile: 26,
  uptime_pct_30d: 100,
  pending_updates: 0,
  backup_status: 'SUCCESS',
  critical_vulns: 0,
};

export const BARNARDOS_DASHBOARD: DashboardData = {
  site: BARNARDOS_SITE,
  snapshot_date: '2026-05-07',
  health_score: 62,
  health_score_delta: null,
  overall_status: 'RED',
  traffic_lights: {
    performance:  'RED',
    security:     'GREEN',
    reliability:  'GREEN',
    updates:      'GREEN',
    backups:      'GREEN',
    engineering:  'GREEN',
  },
  key_metrics: {
    pagespeed_mobile:  26,
    uptime_pct_30d:    100,
    pending_updates:   0,
    backup_status:     'SUCCESS',
    critical_vulns:    0,
    blocked_attacks:   312,
    deploy_count_7d:   2,
    failed_builds_7d:  0,
  },
  category_scores: {
    performance:  18,
    security:     95,
    reliability:  100,
    updates:      100,
    backups:      100,
    engineering:  90,
  },
  recent_incidents: [],
  recent_deployments: [
    {
      id: 'bd1',
      deployed_at: '2026-05-06T10:15:00Z',
      environment: 'PRODUCTION',
      status: 'SUCCESS',
      commit_sha: 'f4a19c3',
      commit_message: 'May M&S: plugin updates, security review, PHP 8.2 upgrade',
      branch: 'main',
      pr_title: 'Maintenance: May M&S — plugins + PHP upgrade',
      deployed_by: 'Wordie',
      is_hotfix: false,
    },
    {
      id: 'bd2',
      deployed_at: '2026-05-06T09:00:00Z',
      environment: 'STAGING',
      status: 'SUCCESS',
      commit_sha: 'e2d88b1',
      commit_message: 'Staging: validate plugin updates before production deploy',
      branch: 'staging',
      pr_title: 'Staging validation: May M&S',
      deployed_by: 'Wordie',
      is_hotfix: false,
    },
  ],
};

export const BARNARDOS_TREND: TrendPoint[] = [
  { snapshot_date: '2026-01-07', health_score: 58, performance_score: 15, security_score: 88, reliability_score: 100, pagespeed_mobile: 22, uptime_pct_30d: 100 },
  { snapshot_date: '2026-02-07', health_score: 59, performance_score: 16, security_score: 90, reliability_score: 100, pagespeed_mobile: 23, uptime_pct_30d: 100 },
  { snapshot_date: '2026-03-07', health_score: 60, performance_score: 17, security_score: 91, reliability_score: 100, pagespeed_mobile: 24, uptime_pct_30d: 100 },
  { snapshot_date: '2026-04-07', health_score: 60, performance_score: 17, security_score: 92, reliability_score: 100, pagespeed_mobile: 25, uptime_pct_30d: 100 },
  { snapshot_date: '2026-05-07', health_score: 62, performance_score: 18, security_score: 95, reliability_score: 100, pagespeed_mobile: 26, uptime_pct_30d: 100 },
];

// ─── Barnardos May 2026 Monthly Report (real PageSpeed data: 26/100 mobile) ──
export const BARNARDOS_REPORT: MonthlyReport = {
  id: 'barnardos-r1',
  website_id: 'barnardos',
  report_month: '2026-05',
  health_score: 62,
  health_score_prev: 60,
  overall_status: 'RED',
  client_name: 'Barnardos Australia',
  domain: 'barnardosaudev.wpengine.com',
  generated_at: '2026-05-07T10:00:00Z',
  report_json: {
    report_month: '2026-05',
    generated_at: '2026-05-07T10:00:00Z',
    executive_summary: {
      health_score: 62,
      health_score_prev: 60,
      overall_status: 'RED',
      highlights: [
        'Site availability was 100% — no downtime events this month',
        'All backups completed successfully every day',
        'Maintenance completed: plugins updated and PHP upgraded to 8.2',
        '0 critical security vulnerabilities detected',
      ],
      key_risks: [
        'Mobile page speed is 26/100 — significantly below the acceptable threshold of 60',
        'Total Blocking Time of 970ms is causing slow page interactivity for visitors',
        'Heavy JavaScript loading (jQuery, Bootstrap, FontAwesome) is the primary cause of poor performance',
        'SEO score of 61/100 may be limiting organic search visibility',
      ],
      month_summary: 'May maintenance was completed successfully — all plugins are current, PHP has been upgraded to 8.2, and the site remained available 100% of the time. However, website performance on mobile devices is a significant concern. The site scores 26/100 on Google\'s mobile speed test, which is well below the threshold where search rankings and visitor experience are affected. The root cause is a large amount of JavaScript loading before the page becomes usable, including third-party scripts and legacy libraries. A performance remediation plan is recommended as the immediate next step.',
    },
    performance: {
      status: 'RED',
      score: 18,
      headline: 'Mobile performance requires urgent attention',
      interpretation: 'Barnardos Australia scores 26/100 on Google\'s mobile page speed test, taken live on 7 May 2026. This is in the poor range. The main cause is 970ms of Total Blocking Time — JavaScript resources are preventing the page from becoming interactive for nearly a full second after the initial load. The primary offenders are large bundled scripts: Bootstrap, FontAwesome icons, jQuery, and a Convert Experiments analytics script that adds 780ms on its own. Together, these resources account for over 15 seconds of network loading time.',
      risk: 'High risk. Google uses mobile page speed as a ranking factor. A score of 26 is likely suppressing organic search traffic and increasing bounce rates — visitors who have to wait too long simply leave.',
      recommended_action: 'Performance remediation is the priority for June. Quick wins: defer the Convert Experiments script, lazy-load FontAwesome, and enable WP Engine\'s Smart Plugin Manager for ongoing optimisation. Expected improvement with these changes alone: +20–30 points.',
      trend: 'STABLE',
      metrics: [
        { key: 'pagespeed_mobile',  label: 'PageSpeed (Mobile)',       value: 26,     unit: '/100', status: 'RED',   description: 'Significantly below the acceptable minimum of 60' },
        { key: 'lcp_mobile',        label: 'Largest Contentful Paint', value: '2.6',  unit: 's',    status: 'AMBER', description: 'Just over the 2.5s good threshold — acceptable but improvable' },
        { key: 'tbt',               label: 'Total Blocking Time',      value: 970,    unit: 'ms',   status: 'RED',   description: 'Heavy JavaScript is blocking interactivity for nearly 1 second' },
        { key: 'cls_mobile',        label: 'Layout Stability (CLS)',   value: '0.104',               status: 'AMBER', description: 'Content shifts slightly while loading — just over the 0.1 threshold' },
        { key: 'fcp_mobile',        label: 'First Contentful Paint',   value: '0.8',  unit: 's',    status: 'GREEN', description: 'First content appears quickly — server response is fast' },
        { key: 'speed_index',       label: 'Speed Index',              value: '4.0',  unit: 's',    status: 'RED',   description: 'Page takes 4 seconds to visually appear complete for visitors' },
      ],
    },
    security: {
      status: 'GREEN',
      score: 95,
      headline: 'Security posture is strong',
      interpretation: 'No critical vulnerabilities were detected this month. The WP Engine firewall blocked 312 attack attempts automatically. All plugins were updated as part of this month\'s maintenance work, removing known vulnerability exposure. The SSL certificate is valid.',
      risk: 'Low security risk. Site is well protected by WP Engine\'s enterprise firewall.',
      recommended_action: null,
      trend: 'IMPROVING',
      metrics: [
        { key: 'vulnerabilities',  label: 'Known Vulnerabilities',   value: 0,              status: 'GREEN', description: 'No vulnerabilities in plugins or themes' },
        { key: 'blocked_attacks',  label: 'Blocked Attacks (30 days)', value: 312,           status: 'GREEN', description: 'All attacks blocked automatically by WP Engine firewall' },
        { key: 'ssl',              label: 'SSL Certificate',          value: 'Valid',         status: 'GREEN', description: 'SSL certificate is valid and auto-renewing' },
        { key: 'security_alerts', label: 'Open Security Alerts',     value: 0,              status: 'GREEN', description: 'No open alerts in the codebase' },
      ],
    },
    reliability: {
      status: 'GREEN',
      score: 100,
      headline: 'Site is stable and fully available',
      interpretation: 'Barnardos Australia had 100% uptime in May with no incidents or downtime events. The site was accessible to every visitor at all times. WP Engine\'s hosting infrastructure performed as expected.',
      risk: 'No reliability risk.',
      recommended_action: null,
      trend: 'STABLE',
      metrics: [
        { key: 'uptime_30d',    label: 'Uptime (30 days)',    value: '100.00', unit: '%',  status: 'GREEN', description: 'No downtime recorded' },
        { key: 'incidents',     label: 'Incidents this month', value: 0,                  status: 'GREEN', description: 'No incidents this month' },
        { key: 'response_time', label: 'Server Response Time', value: 'Fast',             status: 'GREEN', description: 'FCP of 0.8s confirms fast server response' },
      ],
    },
    updates: {
      status: 'GREEN',
      score: 100,
      headline: 'All software is current',
      interpretation: 'All plugin updates were applied during this month\'s maintenance window. PHP has been upgraded to 8.2, which is an actively supported version receiving full security and bug fixes. WordPress core is up to date.',
      risk: 'No technical debt risk from outdated software.',
      recommended_action: null,
      trend: 'IMPROVING',
      metrics: [
        { key: 'wp_core',         label: 'WordPress Core',    value: 'Up to date', status: 'GREEN', description: 'Running the latest WordPress version' },
        { key: 'plugins',         label: 'Plugin Updates',    value: 0,            status: 'GREEN', description: 'All plugins updated during May M&S window' },
        { key: 'php_version',     label: 'PHP Version',       value: '8.2',        status: 'GREEN', description: 'PHP 8.2 is actively supported until Dec 2026' },
      ],
    },
    backups: {
      status: 'GREEN',
      score: 100,
      headline: 'Backups are healthy and current',
      interpretation: 'WP Engine daily backups completed successfully every day in May. The site can be restored to any point within the last 30 days. A pre-maintenance backup was taken before plugin updates were applied.',
      risk: 'Low risk. Full recovery is available from any point this month.',
      recommended_action: null,
      trend: 'STABLE',
      metrics: [
        { key: 'backup_status', label: 'Last Backup Status', value: 'SUCCESS', status: 'GREEN', description: 'Most recent backup completed successfully' },
        { key: 'backup_age',    label: 'Backup Age',         value: 'Today',   status: 'GREEN', description: 'Fresh daily backup available' },
        { key: 'retention',     label: 'Retention Period',   value: '30 days', status: 'GREEN', description: 'WP Engine retains 30 days of daily backups' },
      ],
    },
    engineering: {
      status: 'GREEN',
      score: 90,
      headline: 'Maintenance completed cleanly',
      interpretation: 'This month\'s maintenance was completed with 2 deployments — a staging validation and a production deployment. No failed builds or emergency fixes were required. All changes were tested on staging before going live.',
      risk: 'No engineering risk.',
      recommended_action: null,
      trend: 'STABLE',
      metrics: [
        { key: 'deploys',       label: 'Deployments',         value: 2, status: 'GREEN', description: '1 staging + 1 production — both successful' },
        { key: 'failed_builds', label: 'Failed Deployments',  value: 0, status: 'GREEN', description: 'All deployments succeeded' },
        { key: 'hotfixes',      label: 'Hotfixes Required',   value: 0, status: 'GREEN', description: 'No emergency fixes required' },
      ],
    },
    recommended_actions: [
      {
        priority: 'HIGH',
        category: 'Performance',
        action: 'Defer Convert Experiments analytics script and lazy-load FontAwesome icons. These two changes alone account for ~1,560ms of blocking time.',
        business_impact: 'Expected +15–20 PageSpeed points. Google uses mobile speed as a ranking factor — this directly impacts organic search traffic.',
      },
      {
        priority: 'HIGH',
        category: 'Performance',
        action: 'Audit and remove unused CSS from Bootstrap and replace with utility-only classes. Current dashicons.min.css and fontawesome.min.css total 47KB of render-blocking CSS.',
        business_impact: 'Reducing render-blocking CSS improves Speed Index and LCP, making the page feel significantly faster to visitors.',
      },
      {
        priority: 'MEDIUM',
        category: 'Performance',
        action: 'Enable WP Engine\'s Smart Plugin Manager and CDN caching rules. Configure cache-busting headers for static assets.',
        business_impact: 'Low-effort infrastructure changes with meaningful impact on repeat visitor load times.',
      },
      {
        priority: 'MEDIUM',
        category: 'Performance',
        action: 'Review jQuery dependency — consider removing jQuery Migrate (5.2KB) as no legacy jQuery code should require it on a current WordPress build.',
        business_impact: 'Reduces page weight and eliminates an unnecessary legacy dependency.',
      },
    ],
  },
};

export const MOCK_SITES: Site[] = [
  BARNARDOS_SITE,
  {
    id: '1',
    slug: 'acme-corp',
    client_name: 'Acme Corporation',
    domain: 'acmecorp.com.au',
    active: true,
    health_score: 87,
    traffic_light: 'AMBER',
    last_snapshot: '2026-05-06',
    pagespeed_mobile: 74,
    uptime_pct_30d: 99.95,
    pending_updates: 4,
    backup_status: 'SUCCESS',
    critical_vulns: 0,
  },
  {
    id: '2',
    slug: 'brighton-dental',
    client_name: 'Brighton Dental',
    domain: 'brightondental.com.au',
    active: true,
    health_score: 94,
    traffic_light: 'GREEN',
    last_snapshot: '2026-05-06',
    pagespeed_mobile: 88,
    uptime_pct_30d: 100,
    pending_updates: 1,
    backup_status: 'SUCCESS',
    critical_vulns: 0,
  },
  {
    id: '3',
    slug: 'metro-legal',
    client_name: 'Metro Legal Group',
    domain: 'metrolegal.com.au',
    active: true,
    health_score: 61,
    traffic_light: 'RED',
    last_snapshot: '2026-05-06',
    pagespeed_mobile: 52,
    uptime_pct_30d: 98.7,
    pending_updates: 12,
    backup_status: 'FAILED',
    critical_vulns: 1,
  },
  {
    id: '4',
    slug: 'north-sydney-physio',
    client_name: 'North Sydney Physio',
    domain: 'northsydneyphysio.com.au',
    active: true,
    health_score: 91,
    traffic_light: 'GREEN',
    last_snapshot: '2026-05-06',
    pagespeed_mobile: 82,
    uptime_pct_30d: 99.99,
    pending_updates: 2,
    backup_status: 'SUCCESS',
    critical_vulns: 0,
  },
];

export const MOCK_DASHBOARD: DashboardData = {
  site: MOCK_SITES[0],
  snapshot_date: '2026-05-06',
  health_score: 87,
  health_score_delta: +4,
  overall_status: 'AMBER',
  traffic_lights: {
    performance:  'AMBER',
    security:     'GREEN',
    reliability:  'GREEN',
    updates:      'AMBER',
    backups:      'GREEN',
    engineering:  'GREEN',
  },
  key_metrics: {
    pagespeed_mobile:  74,
    uptime_pct_30d:    99.95,
    pending_updates:   4,
    backup_status:     'SUCCESS',
    critical_vulns:    0,
    blocked_attacks:   847,
    deploy_count_7d:   3,
    failed_builds_7d:  0,
  },
  category_scores: {
    performance:  68,
    security:     95,
    reliability:  98,
    updates:      72,
    backups:      100,
    engineering:  92,
  },
  recent_incidents: [
    {
      id: 'i1',
      type: 'PERFORMANCE',
      severity: 'MEDIUM',
      title: 'Elevated response times detected',
      started_at: '2026-05-02T14:22:00Z',
      resolved_at: '2026-05-02T15:44:00Z',
      duration_minutes: 82,
      impact_summary: 'Pages took up to 3.2 seconds longer than usual to load for 82 minutes due to a third-party script issue.',
    },
  ],
  recent_deployments: [
    {
      id: 'd1',
      deployed_at: '2026-05-05T09:30:00Z',
      environment: 'PRODUCTION',
      status: 'SUCCESS',
      commit_sha: 'a3f92c1',
      commit_message: 'Update contact form validation and add new team page',
      branch: 'main',
      pr_title: 'Feature: Team page + contact form fix',
      deployed_by: 'Stewart L',
      is_hotfix: false,
    },
    {
      id: 'd2',
      deployed_at: '2026-05-01T16:10:00Z',
      environment: 'PRODUCTION',
      status: 'SUCCESS',
      commit_sha: 'b8e14d7',
      commit_message: 'Apply April plugin updates',
      branch: 'main',
      pr_title: 'Maintenance: April plugin updates',
      deployed_by: 'Stewart L',
      is_hotfix: false,
    },
  ],
};

export const MOCK_TREND: TrendPoint[] = [
  { snapshot_date: '2026-04-07', health_score: 79, performance_score: 58, security_score: 90, reliability_score: 98, pagespeed_mobile: 61, uptime_pct_30d: 99.87 },
  { snapshot_date: '2026-04-14', health_score: 81, performance_score: 62, security_score: 92, reliability_score: 99, pagespeed_mobile: 65, uptime_pct_30d: 99.91 },
  { snapshot_date: '2026-04-21', health_score: 83, performance_score: 65, security_score: 93, reliability_score: 99, pagespeed_mobile: 70, uptime_pct_30d: 99.93 },
  { snapshot_date: '2026-04-28', health_score: 83, performance_score: 66, security_score: 94, reliability_score: 98, pagespeed_mobile: 71, uptime_pct_30d: 99.95 },
  { snapshot_date: '2026-05-05', health_score: 87, performance_score: 68, security_score: 95, reliability_score: 100, pagespeed_mobile: 74, uptime_pct_30d: 99.95 },
];

export const MOCK_REPORT: MonthlyReport = {
  id: 'r1',
  website_id: '1',
  report_month: '2026-04',
  health_score: 83,
  health_score_prev: 79,
  overall_status: 'AMBER',
  client_name: 'Acme Corporation',
  domain: 'acmecorp.com.au',
  generated_at: '2026-05-01T06:00:00Z',
  report_json: {
    report_month: '2026-04',
    generated_at: '2026-05-01T06:00:00Z',
    executive_summary: {
      health_score: 83,
      health_score_prev: 79,
      overall_status: 'AMBER',
      highlights: [
        'Uptime was 99.91% — no significant downtime events',
        'All backups completed successfully every day',
        '3 successful deployments with no failures',
      ],
      key_risks: [
        'Mobile page speed is below the recommended threshold of 80',
        '4 plugin updates are pending and should be applied',
      ],
      month_summary: 'April was a stable month for your website. The site remained highly available and all backups completed successfully. Performance on mobile devices remains the main area requiring attention, with your PageSpeed score sitting at 71 — below the recommended 80 threshold. A plan to address this has been included below.',
    },
    performance: {
      status: 'AMBER',
      score: 66,
      headline: 'Performance needs attention',
      interpretation: 'Your website scores 71/100 on mobile page speed, which is below the recommended threshold of 80. The main contributing factor is image optimisation and a third-party analytics script loading on page start.',
      risk: 'Moderate risk. Slower load times can reduce search visibility and increase bounce rates.',
      recommended_action: 'Schedule image optimisation and defer the analytics script load. Expected improvement: +12–15 points.',
      trend: 'IMPROVING',
      metrics: [
        { key: 'pagespeed_mobile', label: 'PageSpeed (Mobile)', value: 71, unit: '/100', status: 'AMBER', description: 'Below the recommended threshold of 80' },
        { key: 'lcp_mobile', label: 'Largest Contentful Paint', value: '2.8', unit: 's', status: 'AMBER', description: 'Slightly over the 2.5s good threshold' },
        { key: 'inp_mobile', label: 'Interaction to Next Paint', value: 145, unit: 'ms', status: 'GREEN', description: 'Site responds quickly to taps and clicks' },
        { key: 'cls_mobile', label: 'Layout Stability', value: '0.05', status: 'GREEN', description: 'Content stays in place while loading' },
      ],
    },
    security: {
      status: 'GREEN',
      score: 93,
      headline: 'Security posture is strong',
      interpretation: 'No vulnerabilities were detected this month. Your firewall blocked 847 attack attempts, all automatically. SSL certificate is valid with 289 days remaining.',
      risk: 'Low security risk. Site is well-protected.',
      recommended_action: null,
      trend: 'STABLE',
      metrics: [
        { key: 'vulnerabilities', label: 'Known Vulnerabilities', value: 0, status: 'GREEN', description: 'No vulnerabilities found' },
        { key: 'blocked_attacks', label: 'Blocked Attacks (30 days)', value: '847', status: 'GREEN', description: 'All attacks blocked by firewall' },
        { key: 'ssl', label: 'SSL Certificate', value: 'Valid (289 days)', status: 'GREEN', description: 'Certificate is valid and auto-renews' },
        { key: 'security_alerts', label: 'Open Security Alerts', value: 0, status: 'GREEN', description: 'No open alerts in codebase' },
      ],
    },
    reliability: {
      status: 'GREEN',
      score: 99,
      headline: 'Site is stable and available',
      interpretation: 'Your website was available 99.91% of the time in April. There were no significant downtime events. The one performance incident on April 2nd was resolved within 82 minutes.',
      risk: 'No reliability risk.',
      recommended_action: null,
      trend: 'STABLE',
      metrics: [
        { key: 'uptime_30d', label: 'Uptime (30 days)', value: '99.91', unit: '%', status: 'GREEN', description: 'Excellent availability' },
        { key: 'incidents_7d', label: 'Incidents (month)', value: 1, status: 'AMBER', description: '1 performance incident, resolved in 82 minutes' },
        { key: 'response_time', label: 'Avg Response Time', value: 186, unit: 'ms', status: 'GREEN', description: 'Server responds quickly' },
      ],
    },
    updates: {
      status: 'AMBER',
      score: 72,
      headline: 'Some updates are overdue',
      interpretation: 'WordPress core is up to date. However, 4 plugin updates are pending. These updates include security patches and bug fixes that should be applied in the next maintenance window.',
      risk: 'Moderate risk. Outdated plugins can contain known vulnerabilities.',
      recommended_action: 'Apply 4 pending plugin updates during next maintenance window.',
      trend: 'STABLE',
      metrics: [
        { key: 'wp_core', label: 'WordPress Core', value: 'Up to date', status: 'GREEN', description: 'Running the latest WordPress version' },
        { key: 'plugins', label: 'Plugin Updates', value: 4, status: 'AMBER', description: '4 updates pending including Yoast SEO and WooCommerce' },
        { key: 'php_version', label: 'PHP Version', value: '8.2', status: 'GREEN', description: 'PHP 8.2 is actively supported' },
      ],
    },
    backups: {
      status: 'GREEN',
      score: 100,
      headline: 'Backups are healthy and current',
      interpretation: 'Daily backups completed successfully every day in April. In the event of any incident, your website can be restored to any point within the last 30 days.',
      risk: 'Low risk. Site can be recovered quickly from any incident.',
      recommended_action: null,
      trend: 'STABLE',
      metrics: [
        { key: 'backup_status', label: 'Last Backup Status', value: 'SUCCESS', status: 'GREEN', description: 'Most recent backup completed successfully' },
        { key: 'backup_age', label: 'Backup Age', value: '14h ago', status: 'GREEN', description: 'Fresh backup available' },
      ],
    },
    engineering: {
      status: 'GREEN',
      score: 92,
      headline: 'Engineering activity is healthy',
      interpretation: '3 successful deployments this month with no failures. Changes were tested on staging before going live. No emergency fixes were required.',
      risk: 'No engineering risk.',
      recommended_action: null,
      trend: 'STABLE',
      metrics: [
        { key: 'deploys', label: 'Deployments', value: 3, status: 'GREEN', description: '3 successful deployments this month' },
        { key: 'failed_builds', label: 'Failed Deployments', value: 0, status: 'GREEN', description: 'All deployments succeeded' },
        { key: 'hotfixes', label: 'Hotfixes', value: 0, status: 'GREEN', description: 'No emergency fixes required' },
      ],
    },
    recommended_actions: [
      {
        priority: 'MEDIUM',
        category: 'Performance',
        action: 'Schedule image optimisation and defer analytics script load.',
        business_impact: 'Expected +12–15 PageSpeed points. Improves search ranking and reduces bounce rate.',
      },
      {
        priority: 'MEDIUM',
        category: 'Updates',
        action: 'Apply 4 pending plugin updates in next maintenance window.',
        business_impact: 'Reduces security exposure from outdated plugin vulnerabilities.',
      },
    ],
  },
};
